Repository FatecCoderHood/4_Back, pull requests merged in 2025-03, with the labels that each got.

#4 feat <VIS-70> [Banco]:Criação da conexão com o cloud.
  pom.xml
  src/main/java/coderhood/DemoApplication.java
  src/main/resources/application.properties
  wallet/README
  wallet/cwallet.sso
  wallet/ewallet.p12
  wallet/ewallet.pem
  wallet/keystore.jks
  wallet/ojdbc.properties
  wallet/sqlnet.ora
  wallet/tnsnames.ora
  wallet/truststore.jks
Labels: functionality

#3 feat <VIS-55> [Backend]: Criar entidade Area
  src/main/java/coderhood/Application.java
  src/main/java/coderhood/controller/AreaController.java
  src/main/java/coderhood/dto/UserRequestDto.java
  src/main/java/coderhood/dto/UserResponseDto.java
  src/main/java/coderhood/exception/MessageException.java
  src/main/java/coderhood/model/Area.java
  src/main/java/coderhood/model/User.java
  src/main/java/coderhood/repository/AreaRepository.java
  src/main/java/coderhood/service/AreaService.java
  src/main/resources/application.properties
Labels: functionality

#7 feat <VIS-58> [Backend]: Criar controller Area: Criação de controller…
  src/main/java/coderhood/model/Area.java
Labels: enhancement

#9 fix <VIS-70> [Banco]:Criação da conexão com o cloud.
  pom.xml
Labels: enhancement

#10 chore <VIS-23>: Spring security credentials default
  src/main/resources/application.properties
Labels: bug, enhancement

#12 feat <VIS-23>: Add swagger api
  pom.xml
  src/main/java/coderhood/controller/AreaController.java
  src/main/java/coderhood/controller/UserController.java
Labels: documentation

#14 feat <VIS-65> [Backend]: Importar arquivos .geojson e Cadastrar novas…
  src/main/java/coderhood/controller/AreaController.java
  src/main/java/coderhood/dto/AreaDto.java
  src/main/java/coderhood/model/Area.java
  src/main/java/coderhood/service/AreaService.java
  src/main/java/coderhood/service/GeoJsonService.java
  src/main/resources/application.properties
Labels: enhancement, functionality

#16 feat <VIS-64> [Backend]: desenhar .geojson
  pom.xml
  src/main/java/coderhood/controller/AreaController.java
  src/main/java/coderhood/dto/GeoJsonDto.java
  src/main/java/coderhood/service/AreaService.java
  src/main/java/coderhood/service/GeoJsonService.java
Labels: enhancement, functionality

#17 feat <VIS-1> Cadastrar novos usuários
  src/main/java/coderhood/config/passwordConfig.java
  src/main/java/coderhood/controller/UserController.java
  src/main/java/coderhood/dto/UserCreateDto.java
  src/main/java/coderhood/dto/UserRequestDto.java
  src/main/java/coderhood/dto/UserResponseDto.java
  src/main/java/coderhood/dto/UserUpdateDto.java
  src/main/java/coderhood/exception/BusinessRuleException.java
  src/main/java/coderhood/exception/MessageException.java
  src/main/java/coderhood/exception/ResourceNotFoundException.java
  src/main/java/coderhood/model/User.java
  src/main/java/coderhood/repository/UserRepository.java
  src/main/java/coderhood/service/UserService.java
Labels: enhancement, functionality
